version: '3.7'

services:
  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:16.3
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  app_db_data:
    driver: "local"
